"""first

Revision ID: 5197c0db95fc
Revises: 
Create Date: 2022-03-27 23:35:40.478726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5197c0db95fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_password', sa.String(length=200), nullable=False))
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('user', 'user_password')
    # ### end Alembic commands ###
