"""xxx

Revision ID: 5d626edb892b
Revises: 92b3333dfcb9
Create Date: 2022-04-03 01:50:28.226814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d626edb892b'
down_revision = '92b3333dfcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_password')
    # ### end Alembic commands ###
