"""first

Revision ID: 92b3333dfcb9
Revises: 5197c0db95fc
Create Date: 2022-03-27 23:43:02.548619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92b3333dfcb9'
down_revision = '5197c0db95fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_password', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
