HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'flask_qa1'
USERNAME = 'root'
PASSWORD = '19950724'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = '1233'

MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS =  False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "2561884482@qq.com"
MAIL_PASSWORD = "exzpkmralglzeaja"
MAIL_DEFAULT_SENDER = "2561884482@qq.com"
